### ISSUE TITLE
How can I create a watermark image at the center of the page

### ISSUE THREAD

**Issue by hoba-dafidi** [QuestPDF/example-invoice#1]
I have been trying to make a watermark, but never success. Is there any way to go about it?

**Comment by MarcinZiabek** [comment]
Hello! Please try the `Layers` element that allows drawing additional stuff behind and on top of the main content. [A simple example can be found here](https://www.questpdf.com/documentation/api-reference.html#layers) 😁

**Comment by MarcinZiabek** [comment]
The QuestPDF 2022.03 provides additional API methods to implement watermark on entire page. [Please take a look here](https://www.questpdf.com/documentation/api-reference.html#watermark-slots).

**Comment by hoba-dafidi** [comment]
Hello Marcin,
Thank you for this update. It really means alot to me.

David

**Comment by MarcinZiabek** [comment]
That's great! Closing 😁
