### ISSUE TITLE
Dead link/image in readme.md

### ISSUE THREAD

**Issue by turbanoff** [QuestPDF/example-invoice#7]
`readme.md` has an image with link `https://raw.githubusercontent.com/QuestPDF/QuestPDF-Documentation/main/images/minimal-api.png`
But it's dead now - 404.
So it looks like this:
![изображение](https://user-images.githubusercontent.com/741251/181496464-085a6fdc-7b52-4cc9-b0a3-b814483b026d.png)

**Comment by MarcinZiabek** [comment]
You are right! Fixed 😁
